apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: gmod
spec:
  replicas: 2
  template:
    spec:
      ports:
        - name: default
          portPolicy: Passthrough
      template:
        spec:
          containers:
            - name: gmod
              image: seanboult/gmod
              resources:
                requests:
                  memory: "512Mi"
                  cpu: 500m
                limits:
                  memory: "1.5Gi"
                  cpu: 500m
