apiVersion: "agones.dev/v1"
kind: GameServer
metadata:
  generateName: gmod-
spec:
  ports:
    - name: default
      portPolicy: Passthrough
  health:
    initialDelaySeconds: 30
    periodSeconds: 35
  template:
    spec:
      containers:
        - name: gmod
          image: seanboult/gmod
          imagePullPolicy: Always
          stdin: true
          tty: true
          resources:
            requests:
              memory: "512Mi"
              cpu: 500m
            limits:
              memory: "1.5Gi"
              cpu: 500m
