apiVersion: "agones.dev/v1"
kind: GameServer
metadata:
  generateName: tf2-
spec:
  ports:
    - name: default
      portPolicy: Dynamic
      containerPort: 27015
  health:
    disabled: false
    initialDelaySeconds: 30
    periodSeconds: 35
  template:
    spec:
      containers:
        - name: gmod
          image: gcr.io/sandbox-275801/tf2
          imagePullPolicy: Always
          stdin: true
          tty: true
          resources:
            requests:
              memory: "512Mi"
              cpu: "20m"
            limits:
              memory: "1G"
              cpu: "20m"
